### ISSUE TITLE
Support new way to provide potions on upgrade waves in 1.9?

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#291]
Currently upgrade waves are pointless since there are no potion IDs in 1.9. You can't provide potions to everyone. Need to look into an alternative way to provide potions for upgrade waves?

**Comment by garbagemule** [comment]
Perhaps it's time to revisit the idea of grantables.

All I know about potions is that "they don't work", but no one that I have spoken to has mentioned anything about how they are created programmatically now. That'd be the first step.

**Comment by TheComputerGeek2** [comment]
I seem to recall that they use nbt fields rather than the damage value on the item. If you want, I can look up in more detail what the nbt structure is for them, although the bukkit api provides a nice interface for this with the item meta and potion meta interfaces.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/ItemMeta.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/PotionMeta.html
You can go about obtaining the PotionMeta from the item stack with getItemMeta as shown in the link below.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemStack.html#getItemMeta%28%29
The getItemMeta should return a potion meta when the item is a potion. Then you can do whatever you like with the meta and then re apply it to the itemstack.
As far as I can tell, this should work just fine in 1.9.

Is that of any assistance?

**Comment by garbagemule** [comment]
Great stuff! I've only taken a quick look at it, but it does look like this is the way to go about it. Do you know how mature Spigot's 1.9 builds (and more important, the API) are? I really don't want to spend time on something that'll break the next time they sneeze in Spigot land.

I suppose the only other step left would be the actual representations and the parsing. How do other plugins handle this change? Is there a common string representation for, say, a splash potion of healing?

**Comment by TheComputerGeek2** [comment]
I believe that the section of the API that is used here has actually existed prior to 1.9 and has not been marked for removal in the near future. Furthermore, it seems to be part of the Bukkit API, not just the spigot implementation of it. I'm not sure on stability of spigot as a whole yet, but I think that part of it is stable.

As for parsing, I figure that we can base it off of an existing format that you are using:
`[<id>|<name>]:<data>:<amount>`
the data field could be expanded to accommodate for the potion info.
I was thinking like
`[D|S]~<effects>` the D or S would mean drinkable or splash respectively. Then, to expand <effects>
`<effect name>@<amplifier>@<duration>|<effect name>@<amplifier>@<duration>`
using the pipe to separate the different effects.
What we would end up with is `[<id>|<name>]:<effect name>@<amplifier>@<duration>|<effect name>@<amplifier>@<duration>:<amount>`

Now, I realize that this is currently problematic for servers that use custom resource packs to create a use for potions with data values, or I at least would expect that some server does. So to resolve that, we can amend the `[D|S]~<effects>` format to `[D|S]@<dv>~<effects>` with the `@<data value>` being an optional part.

Or, if you really don't want to change the <data> part of the existing format, we could append the potion information to the end of the sequence rather than shoving it in the middle.
For example:
`[<id>|<name>]:<data>:<amount>:<effect name>@<amplifier>@<duration>|<effect name>@<amplifier>@<duration>`

Thoughts? Not sure how other plugins are handling it, mainly because I don't know of many plugins that try to handle it in a single line without just compact yaml. But if you want to go the compact yaml route, by all means, go for it, it can just be a little difficult for some people to get use to. I figured that you would prefer to have minimal changes to the existing syntax.

Hope this helps.

**Comment by garbagemule** [comment]
I think I've come up with a tentative, fairly simple way to solve this. At this point in time, I'd rather release something that works, but may not be feature complete, than keep people waiting.

Basically, I'm leaving the potion _kind_ to the actual material/ID part, so [`potion`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#POTION), [`splash_potion`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#SPLASH_POTION), or [`lingering_potion`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#LINGERING_POTION). Then, the data value part becomes the potion _type_ (or effect), as it is now, but supporting only the [PotionType](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionType.html) enum names, e.g. `instant_heal` for a healing potion, `poison` for a poison potion, etc.

I would really love it if you guys could test out the item parser for me and report back with your findings. Here's a link to a new build: [Super secret Dropbox link](https://dl.dropboxusercontent.com/u/11723967/ma/MobArena.jar).

If you can, please test if the parser works both ways, i.e. reading from the config-file (class items, upgrade waves, etc.), and writing to it (with the setclass command).

Thanks!

**Comment by Bodyash** [comment]
![image](https://cloud.githubusercontent.com/assets/2454569/14584533/6695adf8-0453-11e6-81ba-75d4a7d79145.png)
Cant load plugin with my MEGA config from 1.8 server :sob:

**Comment by Bodyash** [comment]
Working PERFECT with Chest to Inventory items when class selecting!

**Comment by Bodyash** [comment]
Which slot in chest = shield slot?

**Comment by garbagemule** [comment]
Thanks @Bodyash. Could I get you to try and figure out which item is causing this NullPointerException?

Glad to hear the class chests are working. The fifth last slot is for the off-hand item.

**Comment by Bodyash** [comment]
Lost my old config, trying to find

**Comment by Bodyash** [comment]
![default](https://cloud.githubusercontent.com/assets/2454569/14672568/5a689e40-0701-11e6-98b8-af5e7cc1b46c.PNG)
Maybe that, idk, totally lost old config.

And i found some bugs in Chest to Class Inventory

there is no slot for shield?
If u put Elytra to armor slot - elytra will be not autoequiped. 
And 1 bug with Shulker - he can teleport out of arena :D
![2016-04-18_23 06 30](https://cloud.githubusercontent.com/assets/2454569/14672661/e044f52c-0701-11e6-8734-ff871285be04.png)

**Comment by Bodyash** [comment]
Any updates?

**Comment by mibby** [comment]
@garbagemule I'd also like an update if you have anything in the works. :) A fix for classes having potions and restocking waves granting potions is greatly needed!

**Comment by garbagemule** [comment]
@mibby Have you tried the build I linked? Can you get stuff working with it?

**Comment by mibby** [comment]
@garbagemule I actually haven't yet, as I've been using slipcor's fork for this fix. https://github.com/garbagemule/MobArena/pull/288/commits/f11c45cfad83a7ea4843467f315024a3fbeb65e9

Unless your build includes that now?

**Comment by garbagemule** [comment]
That's included, yeah.

I think you might be right that only the "base" potions are supported. If you could test out if they work, I'll try to figure out a way to mix levels in with them as well. It'll probably just boil down to another colon and another number (however utterly unreadable that is).

**Comment by mibby** [comment]
Apologies for the late testing, been busy with work.

Funny enough, the build I have compiled against Slipcor's fork works fine with the old potion IDs in upgrade waves. I'm assuming this is because EssentialsX has a legacy potion remapper? ```[Essentials] Using 1.9+ BasePotionData provider as potion meta provider.```
https://github.com/drtshock/Essentials/commits/2.x

With your custom build, the old potion IDs don't work. :P
```
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:8229:1
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:16418:3
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:16449:3
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:16451:1
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:16450:1
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:16457:1
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:8229:1
[18:24:48] [Server thread/WARN]: [MobArena] Failed to parse item: potion:16385:1
```

Adding the potions via the new method to the upgrade wave does seem to work, at least it does not cause any errors on config reload and arena join.
```
    waves:
      recurrent:
        upgrade1:
          priority: 5
          type: upgrade
          wave: 11
          frequency: 10
          upgrades:
            All: GOLDEN_APPLE, potion:SPEED, splash_potion:instant_heal, LINGERING_POTION:speed
          give-all-items: true
```

As well as adding them to a class via config style instead of classchest seems to work.

```
  Archer:
    items: potion:SPEED:1, splash_potion:instant_heal:1, LINGERING_POTION:speed:1
```

That is assuming this is the syntax it follows.
<potiontype>:<potioneffect>:<amountofpotions>

Besides that, I can not find any way to specify a potion type that is amplified or one that has a different duration. Such as the different splash potion of poison. Splash potion of poison for 0:45, splash potion of poison for 1:30, and splash potion of poison II for 0:21.

**Comment by garbagemule** [comment]
Great stuff!

Yeah, the new build shouldn't support old potion IDs, since it switches on the Material type and goes into "potion parsing" if it's one of the three types of potions. When parsing potions, it only accepts the potion types. I suppose a quick workaround would be to only use the new potion parsing if the data value is not a number, and the default item parsing otherwise.

Do you know if the EssentialsX's legacy mapper applies to all ItemStacks? It seems odd that slip's fork would work unless EssentialsX's mapper is completely ubiquitous.

**Comment by Bodyash** [comment]
Im Using EssentialsX on my server over 5 month. Better that original Essentials.

**Comment by mibby** [comment]
@garbagemule EssentialX's legacy mapper might be completely ubiquitous as I know slipcor didn't specifically fix anything regarding legacy potion IDs in his fork. 

I'd assume this is where the remapper is located.
https://github.com/drtshock/Essentials/blob/8116ce39d7f60e5e1883f59214a10f92a4b2f513/Essentials/src/com/earth2me/essentials/utils/PotionMetaUtil.java

https://github.com/drtshock/Essentials/tree/731455649e134a0a93f2af9b6566d21d26d571cf/nms/UpdatedMetaProvider/src/net/ess3/nms/updatedmeta

https://github.com/drtshock/Essentials/tree/731455649e134a0a93f2af9b6566d21d26d571cf/nms/LegacyProvider/src/net/ess3/nms/legacy

https://github.com/drtshock/Essentials/tree/731455649e134a0a93f2af9b6566d21d26d571cf/nms/NMSProvider/src/net/ess3/nms

**Comment by slipcor** [comment]
mibby, I did fix it :P tl;dr: don't use/read "custom potion effect" but set "main potion effect" - iirc

**Comment by Bodyash** [comment]
New mob type support 1.10 ?

**Comment by garbagemule** [comment]
@Bodyash If Spigot supports the mobs, MobArena does too. Since 0.97, MobArena only needs mob updates for "special" mobs (like elder guardians, which are just guardians with a specific flag on them).

**Comment by Bodyash** [comment]
now zombies ans skeletons has a new sub:type
+ polar bear mob.

**Comment by mibby** [comment]
@slipcor :o When did you fix it? I thought this was the only change to fix class chest loading. https://github.com/garbagemule/MobArena/pull/288

**Comment by slipcor** [comment]
Without putting money on it,  I'd say I fixed inventory assignment, regardless where the definition came from. 
I am not sure if I even knew class chests existed back then oO

**Comment by slipcor** [comment]
Oh @mibby if you were talking about potions, I was referring to fixes in my plugin, not my pull to MA!

**Comment by mibby** [comment]
@slipcor Fixes in your MA fork you sent me or are you talking about PA? :P I'm so confused.

**Comment by slipcor** [comment]
Class items = mobarena
Potions = pvparena

**Comment by mibby** [comment]
Right, so you didn't fix potion IDs in MA with your fork then. Just chest content loading. :P In other words, EssentialsX's legacy ID remapper  may be completely ubiquitous.

**Comment by Bodyash** [comment]
Any updates? 1.10.2 now, and no updates

**Comment by slipcor** [comment]
I just verified that this works on the latest version. For class items, upgrade waves, supply waves and for rewards.

I only tested the old-fashioned way though :P

potion:8197:1

No essentials involved, plain vanilla Spigot 1.11 and MobArena, nothing else!
